title: AI Multi-Agent Toolkit
description: Python 기반 LLM 에이전트 개발을 위한 도구모음과 실용 예제
baseurl: ""
url: "https://jih4855.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Jekyll 3 and GitHub Pages now only support Kramdown for Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

# Include files that would normally be excluded
include:
  - _pages

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"